import os
import datetime
from typing import List, Dict
try:
    from tools.state_manager import StateManager
except ImportError:
    # Handle cases where tools might be imported relatively
    import sys
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from tools.state_manager import StateManager

def report_todos(repo_path: str, findings: List[Dict], agent_name: str = "VibeVaderAgent"):
    """
    Formats and writes the Human-Action-Required report to .exegol/user_action_required.md
    and registers tasks in the StateManager's HITL queue.
    
    Args:
        repo_path: Absolute path to the repository root.
        findings: List of findings from repo_analyzer or other audits.
        agent_name: Name of the agent generating the report.
    """
    md_path = os.path.join(repo_path, ".exegol", "user_action_required.md")
    timestamp = datetime.datetime.now().isoformat()
    
    # Categorize findings
    readiness = [f for f in findings if f.get("category") == "readiness"]
    mocks = [f for f in findings if f.get("category") == "mock"]
    limitations = [f for f in findings if f.get("category") == "limitation"]
    
    md = f"# Exegol V3 - Human Action Required\n"
    md += f"**Generated by:** {agent_name}\n"
    md += f"**Timestamp:** {timestamp}\n\n"
    md += f"> [!CAUTION]\n"
    md += f"> The following items have been flagged as outside the autonomous fleet's operational boundaries.\n"
    md += f"> These require **manual human intervention** to resolve.\n\n"
    
    md += "## 🛠️ Infrastructure & API Readiness\n"
    md += _format_markdown_list(readiness)
    md += "\n"
    
    md += "## 🧪 Mock/Stub Code Detected\n"
    md += _format_markdown_list(mocks)
    md += "\n"
    
    md += "## 🚧 Agentic Limitations & Strategic Debt\n"
    md += _format_markdown_list(limitations)
    md += "\n"
    
    md += "---\n*Vader has spoken. The fleet awaits your command.*\n"
    
    os.makedirs(os.path.dirname(md_path), exist_ok=True)
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md)
        
    # Also update StateManager for UI integration
    try:
        sm = StateManager(repo_path)
        for finding in findings:
            sm.add_hitl_task(
                summary=finding.get("task"),
                category=finding.get("category", "readiness"),
                context=finding.get("context", "Identified by audit.")
            )
    except Exception as e:
        print(f"[todo_reporter] Failed to update StateManager: {e}")

    return f"Report generated with {len(findings)} items at {md_path}"

def _format_markdown_list(findings: List[Dict]) -> str:
    if not findings:
        return "_No items identified in this category._\n"
    
    md = ""
    for f in findings:
        task = f.get('task', 'Unknown Task')
        context = f.get('context', 'Requires human-level oversight.')
        md += f"- [ ] **{task}**\n"
        md += f"  - *Reason:* {context}\n"
    return md

if __name__ == "__main__":
    # Test execution
    import sys
    repo = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    dummy_findings = [
        {"task": "Test Readiness Task", "category": "readiness", "context": "Testing todo_reporter"},
        {"task": "Test Mock Task", "category": "mock", "context": "Testing todo_reporter"},
        {"task": "Test Limitation Task", "category": "limitation", "context": "Testing todo_reporter"}
    ]
    print(report_todos(repo, dummy_findings))
